### ISSUE TITLE
Info Panel | LoC per Day/Month

### ISSUE THREAD

**Issue by Nalun** [IdleGameCompanyTycoon/IdleGameCompanyTycoon#11]

**Comment by Nalun** [comment]
Hier klappt was noch nicht so ganz. Ich glaube die LoC die bei einem Employee angegeben sind sind pro Tag kann das sein? @DustinGDev

**Comment by DustinGDev** [comment]
@Nalun Interessant dass dass zuvor keinem von uns aufgefallen ist ^^ Ist jetzt fixed
